kind: pipeline
type: docker
name: default

workspace:
  base: /go
  path: src/github.com/dotmesh-io/terraform-provider-dotscience

steps:
- name: test
  image: golang:1.13
  environment:
    GO111MODULE: on
  commands:
    - apt-get update && apt-get install -y --no-install-recommends git curl unzip
    - curl -L -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.12.21/terraform_0.12.21_linux_amd64.zip
    - unzip /tmp/terraform.zip -d /usr/local/bin
    - rm -f /tmp/terraform.zip
    - make test
- name: release
  image: golang:1.13
  environment:
    GO111MODULE: on
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN
  commands:
    - git fetch $DRONE_TAG
    - git checkout $DRONE_TAG
    - curl -sL https://git.io/goreleaser | bash
  when:
    event: tag
